# Generated by Django 2.0.2 on 2018-02-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20180216_1518'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='binance',
            unique_together={('trading_pair', 'open_at', 'close_at')},
        ),
        migrations.AddIndex(
            model_name='binance',
            index=models.Index(fields=['trading_pair'], name='poll_binanc_trading_2cf741_idx'),
        ),
        migrations.AddIndex(
            model_name='binance',
            index=models.Index(fields=['trading_pair', 'open_at'], name='poll_binanc_trading_88ba32_idx'),
        ),
    ]
